// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkSMQkFhwLs5-U_LUorr4kk36IAPe1w2g',
    appId: '1:634473576166:web:ebe8b06616103247cded27',
    messagingSenderId: '634473576166',
    projectId: 'learn-flutter-fire-cloud',
    authDomain: 'learn-flutter-fire-cloud.firebaseapp.com',
    storageBucket: 'learn-flutter-fire-cloud.appspot.com',
    measurementId: 'G-3CCFHCLPW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvXPV9duXz1n4NNDfJsETlqc7pDuPkacE',
    appId: '1:634473576166:android:6df8f9f0dfbef227cded27',
    messagingSenderId: '634473576166',
    projectId: 'learn-flutter-fire-cloud',
    storageBucket: 'learn-flutter-fire-cloud.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd-UmBe4ifu7m8g6Ub3w2x3D4xfTAWUak',
    appId: '1:634473576166:ios:cca46ab2c3673892cded27',
    messagingSenderId: '634473576166',
    projectId: 'learn-flutter-fire-cloud',
    storageBucket: 'learn-flutter-fire-cloud.appspot.com',
    iosBundleId: 'com.example.cloudFireStoreLearning',
  );
}
